language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - gem install coveralls-lcov
  - npm install karma karma-coverage karma-jasmine karma-firefox-launcher karma-coveralls
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - opal test py --coverage
after_success:
 # - coveralls-lcov -v -n coverage/Firefox\ 31.0.0\ \(Linux\ 0.0.0\)/lcov.info > coverage/coverage.json
 - coveralls
 # - coveralls --merge=coverage/coverage.json
notifications:
  slack: ohcuk:6spaME3CB7f2PGrMAcklYWqp
